#!/bin/bash

rm result 
touch result

cmd=$1
filename=$2
hash_type=$3

i=1
for line in $(cat $filename); do  
	start=$(date +%s)

	mask=$(awk "NR==${i}" masks)

        echo $line >> result
	echo $line > temp
	rm res 
	touch res

	#echo $mask

	mask=$(awk "NR==${i}" masks)
        $cmd -m $hash_type -a 3 --potfile-disable -o res temp $mask
        cat res >> result

	end=$(date +%s)
	execution_time=$((end-start))
	echo "Execution Time: $execution_time seconds" >> result
	echo >> result

	((i++))
done



