#!/bin/bash

if [ "$(basename $SHELL)" = "zsh" ]; then
    base_dir=$(cd "$(dirname "$0")" && pwd)
else
    base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
fi


if [ "$MSYSTEM" = "MINGW64" ]; then
    echo "This script is running in Git Bash on Windows."
    hashcat_cmd="hashcat64.exe"
    john_cmd="john.exe"
else
    echo "This script is not running in Git Bash on Windows."
    hashcat_cmd="hashcat"
    john_cmd="john"
fi

export HASHCAT_CMD=$hashcat_cmd
export JOHN_CMD=$john_cmd
export PATH=$PATH:$base_dir:$base_dir/hash
export HASH_DIR=$base_dir/hash

echo "Success"
